name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      env:
        Name: tail
        BINDIR: bin
      run: go build -v ./main.go
    
    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*

# 暂时注释掉test环节
#     - name: Test
#       run: go test -v ./...
