name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
#       if: startsWith(github.ref, 'refs/tags/')
      env:
        Name: tail
        BINDIR: bin
      run: go build -o tail ./main.go
    # 发布流程
    - name: Upload Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/*
        # 标签名 必填项
        tag_name: tail

# 暂时注释掉test环节
#     - name: Test
#       run: go test -v ./...
